### ISSUE TITLE
dreamkastが起動しなくなっている

### ISSUE THREAD

**Issue by takaishi** [cloudnativedaysjp/dreamkast#1148]
https://github.com/cloudnativedaysjp/dreamkast/pull/1140 の影響？

```
Exiting
/usr/local/bundle/gems/zeitwerk-2.5.1/lib/zeitwerk/loader/helpers.rb:95:in `const_get': uninitialized constant PrometheusExporter (NameError)
        from /usr/local/bundle/gems/zeitwerk-2.5.1/lib/zeitwerk/loader/helpers.rb:95:in `cget'
        from /usr/local/bundle/gems/zeitwerk-2.5.1/lib/zeitwerk/loader.rb:232:in `block (2 levels) in eager_load'
        from /usr/local/bundle/gems/zeitwerk-2.5.1/lib/zeitwerk/loader/helpers.rb:26:in `block in ls'
        from /usr/local/bundle/gems/zeitwerk-2.5.1/lib/zeitwerk/loader/helpers.rb:18:in `each_child'
        from /usr/local/bundle/gems/zeitwerk-2.5.1/lib/zeitwerk/loader/helpers.rb:18:in `ls'
        from /usr/local/bundle/gems/zeitwerk-2.5.1/lib/zeitwerk/loader.rb:227:in `block in eager_load'
        from /usr/local/bundle/gems/zeitwerk-2.5.1/lib/zeitwerk/loader.rb:212:in `synchronize'
        from /usr/local/bundle/gems/zeitwerk-2.5.1/lib/zeitwerk/loader.rb:212:in `eager_load'
        from /usr/local/bundle/gems/zeitwerk-2.5.1/lib/zeitwerk/loader.rb:312:in `each'
        from /usr/local/bundle/gems/zeitwerk-2.5.1/lib/zeitwerk/loader.rb:312:in `eager_load_all'
        from /usr/local/bundle/gems/railties-6.0.4.1/lib/rails/application/finisher.rb:122:in `block in <module:Finisher>'
        from /usr/local/bundle/gems/railties-6.0.4.1/lib/rails/initializable.rb:32:in `instance_exec'
        from /usr/local/bundle/gems/railties-6.0.4.1/lib/rails/initializable.rb:32:in `run'
        from /usr/local/bundle/gems/railties-6.0.4.1/lib/rails/initializable.rb:61:in `block in run_initializers'
        from /usr/local/lib/ruby/3.0.0/tsort.rb:228:in `block in tsort_each'
        from /usr/local/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /usr/local/lib/ruby/3.0.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /usr/local/lib/ruby/3.0.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /usr/local/lib/ruby/3.0.0/tsort.rb:347:in `each'
        from /usr/local/lib/ruby/3.0.0/tsort.rb:347:in `call'
        from /usr/local/lib/ruby/3.0.0/tsort.rb:347:in `each_strongly_connected_component'
        from /usr/local/lib/ruby/3.0.0/tsort.rb:226:in `tsort_each'
        from /usr/local/lib/ruby/3.0.0/tsort.rb:205:in `tsort_each'
        from /usr/local/bundle/gems/railties-6.0.4.1/lib/rails/initializable.rb:60:in `run_initializers'
        from /usr/local/bundle/gems/railties-6.0.4.1/lib/rails/application.rb:363:in `initialize!'
        from /app/config/environment.rb:5:in `<main>'
        from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        from /usr/local/bundle/gems/zeitwerk-2.5.1/lib/zeitwerk/kernel.rb:35:in `require'
        from /usr/local/bundle/gems/activesupport-6.0.4.1/lib/active_support/dependencies.rb:324:in `block in require'
        from /usr/local/bundle/gems/activesupport-6.0.4.1/lib/active_support/dependencies.rb:291:in `load_dependency'
        from /usr/local/bundle/gems/activesupport-6.0.4.1/lib/active_support/dependencies.rb:324:in `require'
        from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:49:in `require_relative'
        from config.ru:3:in `block in <main>'
        from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
        from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
        from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
        from /usr/local/bundle/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
        from /usr/local/bundle/gems/rack-2.2.3/lib/rack/server.rb:349:in `build_app_and_options_from_config'
        from /usr/local/bundle/gems/rack-2.2.3/lib/rack/server.rb:249:in `app'
        from /usr/local/bundle/gems/rack-2.2.3/lib/rack/server.rb:422:in `wrapped_app'
        from /usr/local/bundle/gems/rack-2.2.3/lib/rack/server.rb:312:in `block in start'
        from /usr/local/bundle/gems/rack-2.2.3/lib/rack/server.rb:379:in `handle_profiling'
        from /usr/local/bundle/gems/rack-2.2.3/lib/rack/server.rb:311:in `start'
        from /usr/local/bundle/gems/railties-6.0.4.1/lib/rails/commands/server/server_command.rb:39:in `start'
        from /usr/local/bundle/gems/railties-6.0.4.1/lib/rails/commands/server/server_command.rb:147:in `block in perform'
        from <internal:kernel>:90:in `tap'
        from /usr/local/bundle/gems/railties-6.0.4.1/lib/rails/commands/server/server_command.rb:138:in `perform'
        from /usr/local/bundle/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
        from /usr/local/bundle/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/local/bundle/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
        from /usr/local/bundle/gems/railties-6.0.4.1/lib/rails/command/base.rb:69:in `perform'
        from /usr/local/bundle/gems/railties-6.0.4.1/lib/rails/command.rb:46:in `invoke'
        from /usr/local/bundle/gems/railties-6.0.4.1/lib/rails/commands.rb:18:in `<main>'
        from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        from /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        from /usr/local/bundle/gems/activesupport-6.0.4.1/lib/active_support/dependencies.rb:324:in `block in require'
        from /usr/local/bundle/gems/activesupport-6.0.4.1/lib/active_support/dependencies.rb:291:in `load_dependency'
        from /usr/local/bundle/gems/activesupport-6.0.4.1/lib/active_support/dependencies.rb:324:in `require'
        from /app/bin/rails:9:in `<top (required)>'
        from /usr/local/bundle/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
        from /usr/local/bundle/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
        from /usr/local/bundle/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
        from /usr/local/bundle/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
        from /usr/local/bundle/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
        from /usr/local/bundle/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
        from /usr/local/bundle/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
        from /app/bin/spring:15:in `require'
        from /app/bin/spring:15:in `<top (required)>'
        from bin/rails:3:in `load'
        from bin/rails:3:in `<main>'
```

**Comment by jacopen** [comment]
現在は直っているので閉じ
