### ISSUE TITLE
Admin>Users>Export to CSVがInternal Server Errorになる

### ISSUE THREAD

**Issue by nabemasat** [cloudnativedaysjp/dreamkast#1976]
状況：
Admin>Usersで「エクスポート」ボタンを押してCSV出力をしようとするとInternal Server Errorになる

登録ユーザーのCSVエクスポートが必要な理由：
インプレス社でメール配信をする際、申込済のメルマガ会員を除外したいとのこと
申込済の会員に同じイベントについてのメルマガが何度も届くと、解約の原因になってしまうため
とのこと

**Comment by nabemasat** [comment]
事務局でも
・参加者への直前案内(8/2配信）
・参加者へのサンキューメール(8/3配信）
の配信の際に必要

**Comment by takaishi** [comment]
```
dreamkast-6c4cb67857-r4tq5 dreamkast E, [2023-07-25T10:34:30.098809 #16] ERROR -- : [5fe666fe-7c16-4e21-a6e0-fed7c6145740] Rendering 500 with exception: Couldn't find FormModels::Industry with ID=3
dreamkast-6c4cb67857-r4tq5 dreamkast E, [2023-07-25T10:34:30.099058 #16] ERROR -- : [5fe666fe-7c16-4e21-a6e0-fed7c6145740] /usr/local/bundle/gems/active_hash-3.1.1/lib/active_hash/relation.rb:55:in `find'
dreamkast-6c4cb67857-r4tq5 dreamkast /usr/local/bundle/gems/active_hash-3.1.1/lib/active_hash/base.rb:198:in `find'
dreamkast-6c4cb67857-r4tq5 dreamkast /app/app/models/profile.rb:151:in `industry_name'
dreamkast-6c4cb67857-r4tq5 dreamkast /app/app/models/profile.rb:121:in `block (2 levels) in export'
dreamkast-6c4cb67857-r4tq5 dreamkast /usr/local/bundle/gems/activerecord-7.0.5/lib/active_record/relation/delegation.rb:88:in `each'
dreamkast-6c4cb67857-r4tq5 dreamkast /usr/local/bundle/gems/activerecord-7.0.5/lib/active_record/relation/delegation.rb:88:in `each'
dreamkast-6c4cb67857-r4tq5 dreamkast /app/app/models/profile.rb:113:in `block in export'
dreamkast-6c4cb67857-r4tq5 dreamkast /usr/local/lib/ruby/3.2.0/csv.rb:1409:in `generate'
dreamkast-6c4cb67857-r4tq5 dreamkast /app/app/models/profile.rb:111:in `export'
dreamkast-6c4cb67857-r4tq5 dreamkast /app/app/controllers/admin/profiles_controller.rb:5:in `export_profiles'
```
