### ISSUE TITLE
docker-compose up時にIntegrity check failedエラーが出て起動しない

### ISSUE THREAD

**Issue by takaishi** [cloudnativedaysjp/dreamkast#28]
```
app_1  | warning Integrity check: System parameters don't match
app_1  | error Integrity check failed
app_1  | error Found 1 errors.
app_1  |
app_1  |
app_1  | ========================================
app_1  |   Your Yarn packages are out of date!
app_1  |   Please run `yarn install --check-files` to update.
app_1  | ========================================
app_1  |
app_1  |
app_1  | To disable this check, please change `check_yarn_integrity`
app_1  | to `false` in your webpacker config file (config/webpacker.yml).
app_1  |
app_1  |
app_1  | yarn check v1.22.4
app_1  | info Visit https://yarnpkg.com/en/docs/cli/check for documentation about this command.
app_1  |
app_1  |
app_1  | => Booting Puma
app_1  | => Rails 6.0.3.1 application starting in development
app_1  | => Run `rails server --help` for more startup options
app_1  | warning Integrity check: System parameters don't match
app_1  | error Integrity check failed
app_1  | error Found 1 errors.
app_1  |
app_1  |
app_1  | ========================================
app_1  |   Your Yarn packages are out of date!
app_1  |   Please run `yarn install --check-files` to update.
app_1  | ========================================
app_1  |
app_1  |
app_1  | To disable this check, please change `check_yarn_integrity`
app_1  | to `false` in your webpacker config file (config/webpacker.yml).
app_1  |
app_1  |
app_1  | yarn check v1.22.4
app_1  | info Visit https://yarnpkg.com/en/docs/cli/check for documentation about this command.
app_1  |
app_1  |
app_1  | Exiting
```

**Comment by takaishi** [comment]
`Please run `yarn install --check-files` to update.` と書かれていたので実行し、再度docker-compose upしたが同様のエラー

```
~/s/g/c/dreamkast $ yarn install --check-files
yarn install v1.22.4
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 1.46s.
```

**Comment by takaishi** [comment]
config/webpacker.yml のdevelopmentで check_yarn_integrity: false に変えると起動するのは起動する

**Comment by takaishi** [comment]
あああああ〜

**Comment by jacopen** [comment]
あー、自分の手元では修正済みでした。まだ上げてなかった

https://github.com/cloudnativedaysjp/dreamkast/blob/29_auth0/Dockerfile#L18

コミット綺麗に分かれてないけど #29 の修正で一緒に入ります

**Comment by takaishi** [comment]
https://github.com/cloudnativedaysjp/dreamkast/pull/30 を手元で試したが、Integrity check failedが引き続き発生する状況

**Comment by jacopen** [comment]
まーじー。
check_yarn_integrity: false　入れちゃってもいいかなぁ

**Comment by takaishi** [comment]
イメージをビルドし直したけど変わらずエラーになりますねえ。なんだろう…

**Comment by takaishi** [comment]
> check_yarn_integrity: false　入れちゃってもいいかなぁ

ひとまず入れてしまってもいいかも知れんすね

**Comment by jacopen** [comment]
入れたので再チェックおねしゃす

**Comment by takaishi** [comment]
integrity checkは通過したがMysql2のコネクションエラーが発生：

```
app_1  | rails aborted!
app_1  | Mysql2::Error::ConnectionError: Access denied for user 'user'@'%' to database 'dreamkast'
app_1  | /usr/local/bundle/gems/mysql2-0.5.3/lib/mysql2/client.rb:90:in `connect'
app_1  | /usr/local/bundle/gems/mysql2-0.5.3/lib/mysql2/client.rb:90:in `initialize'
app_1  | /usr/local/bundle/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `new'
app_1  | /usr/local/bundle/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/mysql2_adapter.rb:24:in `mysql2_connection'
app_1  | /usr/local/bundle/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
app_1  | /usr/local/bundle/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
app_1  | /usr/local/bundle/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
app_1  | /usr/local/bundle/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
app_1  | /usr/local/bundle/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
app_1  | /usr/local/bundle/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
app_1  | /usr/local/bundle/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:1119:in `retrieve_connection'
app_1  | /usr/local/bundle/gems/activerecord-6.0.3.1/lib/active_record/connection_handling.rb:221:in `retrieve_connection'
app_1  | /usr/local/bundle/gems/activerecord-6.0.3.1/lib/active_record/connection_handling.rb:189:in `connection'
app_1  | /usr/local/bundle/gems/activerecord-6.0.3.1/lib/active_record/tasks/database_tasks.rb:238:in `migrate'
app_1  | /usr/local/bundle/gems/activerecord-6.0.3.1/lib/active_record/railties/databases.rake:86:in `block (3 levels) in <main>'
app_1  | /usr/local/bundle/gems/activerecord-6.0.3.1/lib/active_record/railties/databases.rake:84:in `each'
app_1  | /usr/local/bundle/gems/activerecord-6.0.3.1/lib/active_record/railties/databases.rake:84:in `block (2 levels) in <main>'
app_1  | /usr/local/bundle/gems/railties-6.0.3.1/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
app_1  | /usr/local/bundle/gems/railties-6.0.3.1/lib/rails/commands/rake/rake_command.rb:20:in `perform'
app_1  | /usr/local/bundle/gems/railties-6.0.3.1/lib/rails/command.rb:48:in `invoke'
app_1  | /usr/local/bundle/gems/railties-6.0.3.1/lib/rails/commands.rb:18:in `<main>'
app_1  | /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
app_1  | /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
app_1  | /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
app_1  | /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
app_1  | /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
app_1  | /usr/local/bundle/gems/activesupport-6.0.3.1/lib/active_support/dependencies.rb:324:in `block in require'
app_1  | /usr/local/bundle/gems/activesupport-6.0.3.1/lib/active_support/dependencies.rb:291:in `load_dependency'
app_1  | /usr/local/bundle/gems/activesupport-6.0.3.1/lib/active_support/dependencies.rb:324:in `require'
app_1  | /app/bin/rails:9:in `<top (required)>'
app_1  | /usr/local/bundle/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
app_1  | /usr/local/bundle/gems/spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
app_1  | /usr/local/bundle/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
app_1  | /usr/local/bundle/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
app_1  | /usr/local/bundle/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
app_1  | /usr/local/bundle/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `load'
app_1  | /usr/local/bundle/gems/spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
app_1  | /app/bin/spring:15:in `<top (required)>'
app_1  | bin/rails:3:in `load'
app_1  | bin/rails:3:in `<main>'
app_1  | Tasks: TOP => db:migrate
app_1  | (See full trace by running task with --trace)
app_1  | => Booting Puma
app_1  | => Rails 6.0.3.1 application starting in development
app_1  | => Run `rails server --help` for more startup options
app_1  | Puma starting in single mode...
app_1  | * Version 4.3.5 (ruby 2.7.1-p83), codename: Mysterious Traveller
app_1  | * Min threads: 5, max threads: 5
app_1  | * Environment: development
app_1  | * Listening on tcp://0.0.0.0:3000
app_1  | Use Ctrl-C to stop

```

**Comment by takaishi** [comment]
Docker for MacのVM上にMySQL用のVolumeが残っていたのが原因でした。
docker volume rm でボリュームを消して、再度docker-compose upで起動することを確認

**Comment by takaishi** [comment]
次はwebpackコマンドがない、というエラー：

```
app_1  | == 20200616110507 CreateAccessLogs: migrating =================================
app_1  | -- create_table(:access_logs)
app_1  |    -> 0.0103s
app_1  | == 20200616110507 CreateAccessLogs: migrated (0.0104s) ========================
app_1  |
app_1  | => Booting Puma
app_1  | => Rails 6.0.3.1 application starting in development
app_1  | => Run `rails server --help` for more startup options
app_1  | Puma starting in single mode...
app_1  | * Version 4.3.5 (ruby 2.7.1-p83), codename: Mysterious Traveller
app_1  | * Min threads: 5, max threads: 5
app_1  | * Environment: development
app_1  | * Listening on tcp://0.0.0.0:3000
app_1  | Use Ctrl-C to stop
app_1  | Started GET "/" for 172.23.0.1 at 2020-06-24 08:40:18 +0000
app_1  | Cannot render console from 172.23.0.1! Allowed networks: 127.0.0.0/127.255.255.255, ::1
app_1  |    (0.6ms)  SET NAMES utf8,  @@SESSION.sql_mode = CONCAT(CONCAT(@@sql_mode, ',STRICT_ALL_TABLES'), ',NO_AUTO_VALUE_ON_ZERO'),  @@SESSION.sql_auto_is_null = 0, @@SESSION.wait_timeout = 2147483
app_1  |    (0.4ms)  SELECT `schema_migrations`.`version` FROM `schema_migrations` ORDER BY `schema_migrations`.`version` ASC
app_1  | Processing by HomeController#show as HTML
app_1  |   Rendering home/show.html.erb within layouts/application
app_1  |   Rendered home/show.html.erb within layouts/application (Duration: 12.0ms | Allocations: 499)
app_1  | /usr/local/bundle/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:355: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
app_1  | /usr/local/bundle/gems/sprockets-4.0.2/lib/sprockets/base.rb:118: warning: The called method `[]' is defined here
app_1  | [Webpacker] Compiling...
app_1  | [Webpacker] Compilation failed:
app_1  | yarn run v1.22.4
app_1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
app_1  |
app_1  |
app_1  | error Command "webpack" not found.
app_1  |
app_1  | Completed 500 Internal Server Error in 4296ms (ActiveRecord: 0.0ms | Allocations: 282958)
app_1  |
app_1  |
app_1  |
app_1  | ActionView::Template::Error (Webpacker can't find application in /app/public/packs/manifest.json. Possible causes:
app_1  | 1. You want to set webpacker.yml value of compile to true for your environment
app_1  |    unless you are using the `webpack -w` or the webpack-dev-server.
app_1  | 2. webpack has not yet re-run to reflect updates.
app_1  | 3. You have misconfigured Webpacker's config/webpacker.yml file.
app_1  | 4. Your webpack configuration is not creating a manifest.
app_1  | Your manifest contains:
app_1  | {
app_1  | }
app_1  | ):
app_1  |      7:
app_1  |      8:     <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
app_1  |      9:     <%= stylesheet_link_tag 'styles', media: 'all', 'data-turbolinks-track': 'reload' %>
app_1  |     10:     <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
app_1  |     11:
app_1  |     12:   </head>
app_1  |     13:   <body id="page-top">
app_1  |
app_1  | app/views/layouts/application.html.erb:10
```

**Comment by jacopen** [comment]
あー、bundle installしないといけないのか

**Comment by jacopen** [comment]
いや、違うね。bundle installした状態で別環境でためしたら再現した。あれ？

**Comment by takaishi** [comment]
rails webpacker:install が必要なのかな

**Comment by jacopen** [comment]
正解っぽい。
entrypoint.shにbundle installとrails webpacker:install入れたら通った気がする

**Comment by takaishi** [comment]
起動時に毎回rails webpacker:installすると結構時間かかるぽい。これはローカルで一度だけ実行すればいいタイプのものなのかな？

**Comment by jacopen** [comment]
新規に作った環境、webpackは突破したけどログインしようとすると "InvalidAuthenticityToken" が出るようになってしまった。あるぇ

**Comment by jacopen** [comment]
"InvalidAuthenticityToken"が出るのもwebpackがらみな感じ。jQueryが正しく読み込んでおらず、CSRFトークンを正しく送れずにこれが出ちゃう。つら

**Comment by takaishi** [comment]
ひとまず、localhostでrails webpacker:installして起動できたのでその辺りをPRして、このissueはcloseかな

**Comment by jacopen** [comment]
PullReqマージおなしゃす

**Comment by takaishi** [comment]
https://github.com/cloudnativedaysjp/dreamkast/pull/30 をマージして解消したのでclose
