### ISSUE TITLE
スピーカー登録しようとするとInternal Server Errorになる

### ISSUE THREAD

**Issue by nabemasat** [cloudnativedaysjp/dreamkast#471]
すみませんが、こちらご確認頂けると助かります。優先度高めです:bow:

------

http://event.cloudnativedays.jp/cndo2021/speakers/entry 
からスピーカーの代理登録（スポンサー）をしようとしたところ、Internal Server Errorが発生

操作手順
- 上記URLに直接アクセス
- エントリーするボタンを押し、アカウント作成（ログイン）
- エラー

（ほか、登録済みのスピーカーからセッションを編集しようとしたところInternal Server Errorが起きたと報告あり。上記と関連するかは不明）

**Comment by jacopen** [comment]
```
2021-02-15T09:20:43.842256+00:00 app[web.1]: I, [2021-02-15T09:20:43.842179 #10]  INFO -- : [1cf11d12-e77e-4e39-ba47-d597e42e4789] Started GET "/cndo2021/speakers/entry" for 124.36.216.208 at 2021-02-15 09:20:43 +0000
2021-02-15T09:20:43.844298+00:00 app[web.1]: I, [2021-02-15T09:20:43.844229 #10]  INFO -- : [1cf11d12-e77e-4e39-ba47-d597e42e4789] Processing by SpeakerDashboard::SpeakersController#new as HTML
2021-02-15T09:20:43.844433+00:00 app[web.1]: I, [2021-02-15T09:20:43.844370 #10]  INFO -- : [1cf11d12-e77e-4e39-ba47-d597e42e4789]   Parameters: {"event"=>"cndo2021"}
2021-02-15T09:20:43.914857+00:00 app[web.1]: D, [2021-02-15T09:20:43.914714 #10] DEBUG -- : [1cf11d12-e77e-4e39-ba47-d597e42e4789]   [1m[36mConference Exists? (2.9ms)[0m  [1m[34mSELECT 1 AS one FROM `conferences` WHERE `conferences`.`abbr` = 'cndo2021' LIMIT 1[0m
2021-02-15T09:20:43.918861+00:00 app[web.1]: D, [2021-02-15T09:20:43.918780 #10] DEBUG -- : [1cf11d12-e77e-4e39-ba47-d597e42e4789]   [1m[36mConference Load (3.4ms)[0m  [1m[34mSELECT `conferences`.* FROM `conferences` WHERE `conferences`.`abbr` = 'cndo2021' LIMIT 1[0m
2021-02-15T09:20:43.923575+00:00 app[web.1]: D, [2021-02-15T09:20:43.923491 #10] DEBUG -- : [1cf11d12-e77e-4e39-ba47-d597e42e4789]   [1m[36mSpeaker Load (4.0ms)[0m  [1m[34mSELECT `speakers`.* FROM `speakers` WHERE `speakers`.`conference_id` = 2 AND `speakers`.`email` = 'kusama@wells.jp' LIMIT 1[0m
2021-02-15T09:20:43.924871+00:00 app[web.1]: I, [2021-02-15T09:20:43.924799 #10]  INFO -- : [1cf11d12-e77e-4e39-ba47-d597e42e4789]   Rendering speaker_dashboard/speakers/new.html.erb within layouts/application
2021-02-15T09:20:43.928725+00:00 app[web.1]: I, [2021-02-15T09:20:43.928653 #10]  INFO -- : [1cf11d12-e77e-4e39-ba47-d597e42e4789]   Rendered speaker_dashboard/speakers/_form.html.erb (Duration: 3.6ms | Allocations: 1273)
2021-02-15T09:20:43.928829+00:00 app[web.1]: I, [2021-02-15T09:20:43.928778 #10]  INFO -- : [1cf11d12-e77e-4e39-ba47-d597e42e4789]   Rendered speaker_dashboard/speakers/new.html.erb within layouts/application (Duration: 3.9ms | Allocations: 1331)
2021-02-15T09:20:43.928996+00:00 app[web.1]: E, [2021-02-15T09:20:43.928935 #10] ERROR -- : [1cf11d12-e77e-4e39-ba47-d597e42e4789] Rendering 500 with exception: undefined method `avatar_url' for nil:NilClass
2021-02-15T09:20:43.929106+00:00 app[web.1]: E, [2021-02-15T09:20:43.929028 #10] ERROR -- : [1cf11d12-e77e-4e39-ba47-d597e42e4789] /app/app/views/speaker_dashboard/speakers/_form.html.erb:43:in `block in _app_views_speaker_dashboard_speakers__form_html_erb__2313813606917588312_335440'
2021-02-15T09:20:43.929107+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionview-6.0.3.1/lib/action_view/helpers/capture_helper.rb:45:in `block in capture'
2021-02-15T09:20:43.929107+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionview-6.0.3.1/lib/action_view/helpers/capture_helper.rb:209:in `with_output_buffer'
2021-02-15T09:20:43.929108+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionview-6.0.3.1/lib/action_view/helpers/capture_helper.rb:45:in `capture'
2021-02-15T09:20:43.929109+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionview-6.0.3.1/lib/action_view/helpers/form_helper.rb:755:in `form_with'
2021-02-15T09:20:43.929109+00:00 app[web.1]: /app/app/views/speaker_dashboard/speakers/_form.html.erb:3:in `_app_views_speaker_dashboard_speakers__form_html_erb__2313813606917588312_335440'
2021-02-15T09:20:43.929110+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionview-6.0.3.1/lib/action_view/base.rb:274:in `_run'
2021-02-15T09:20:43.929111+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionview-6.0.3.1/lib/action_view/template.rb:185:in `block in render'
2021-02-15T09:20:43.929111+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.1/lib/active_support/notifications.rb:182:in `instrument'
2021-02-15T09:20:43.929112+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionview-6.0.3.1/lib/action_view/template.rb:385:in `instrument_render_template'
2021-02-15T09:20:43.929112+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionview-6.0.3.1/lib/action_view/template.rb:183:in `render'
2021-02-15T09:20:43.929113+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionview-6.0.3.1/lib/action_view/renderer/partial_renderer.rb:357:in `block in render_partial'
2021-02-15T09:20:43.929113+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionview-6.0.3.1/lib/action_view/renderer/abstract_renderer.rb:88:in `block in instrument'
2021-02-15T09:20:43.929114+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.1/lib/active_support/notifications.rb:180:in `block in instrument'
2021-02-15T09:20:43.929114+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
2021-02-15T09:20:43.929115+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.1/lib/active_support/notifications.rb:180:in `instrument'
2021-02-15T09:20:43.929115+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionview-6.0.3.1/lib/action_view/renderer/abstract_renderer.rb:87:in `instrument'
2021-02-15T09:20:43.929116+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionview-6.0.3.1/lib/action_view/renderer/partial_renderer.rb:346:in `render_partial'
2021-02-15T09:20:43.929116+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionview-6.0.3.1/lib/action_view/renderer/partial_renderer.rb:317:in `render'
2021-02-15T09:20:43.929116+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionview-6.0.3.1/lib/action_view/renderer/renderer.rb:65:in `render_partial_to_object'
2021-02-15T09:20:43.929117+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionview-6.0.3.1/lib/action_view/renderer/renderer.rb:53:in `render_partial'
2021-02-15T09:20:43.929117+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionview-6.0.3.1/lib/action_view/helpers/rendering_helper.rb:38:in `render'
2021-02-15T09:20:43.929117+00:00 app[web.1]: /app/app/views/speaker_dashboard/speakers/new.html.erb:5:in `_app_views_speaker_dashboard_speakers_new_html_erb__3707408106048075306_474420'
2021-02-15T09:20:43.929118+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionview-6.0.3.1/lib/action_view/base.rb:274:in `_run'
2021-02-15T09:20:43.929118+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionview-6.0.3.1/lib/action_view/template.rb:185:in `block in render'
2021-02-15T09:20:43.929118+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.1/lib/active_support/notifications.rb:182:in `instrument'
2021-02-15T09:20:43.929119+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionview-6.0.3.1/lib/action_view/template.rb:385:in `instrument_render_template'
2021-02-15T09:20:43.929119+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionview-6.0.3.1/lib/action_view/template.rb:183:in `render'
2021-02-15T09:20:43.929120+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionview-6.0.3.1/lib/action_view/renderer/template_renderer.rb:58:in `block (2 levels) in render_template'
2021-02-15T09:20:43.929120+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionview-6.0.3.1/lib/action_view/renderer/abstract_renderer.rb:88:in `block in instrument'
2021-02-15T09:20:43.929121+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.1/lib/active_support/notifications.rb:180:in `block in instrument'
2021-02-15T09:20:43.929121+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
2021-02-15T09:20:43.929121+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.1/lib/active_support/notifications.rb:180:in `instrument'
2021-02-15T09:20:43.929127+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionview-6.0.3.1/lib/action_view/renderer/abstract_renderer.rb:87:in `instrument'
2021-02-15T09:20:43.929127+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionview-6.0.3.1/lib/action_view/renderer/template_renderer.rb:57:in `block in render_template'
2021-02-15T09:20:43.929128+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionview-6.0.3.1/lib/action_view/renderer/template_renderer.rb:65:in `render_with_layout'
2021-02-15T09:20:43.929128+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionview-6.0.3.1/lib/action_view/renderer/template_renderer.rb:56:in `render_template'
2021-02-15T09:20:43.929129+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionview-6.0.3.1/lib/action_view/renderer/template_renderer.rb:13:in `render'
2021-02-15T09:20:43.929129+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionview-6.0.3.1/lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
2021-02-15T09:20:43.929129+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionview-6.0.3.1/lib/action_view/renderer/renderer.rb:29:in `render_to_object'
2021-02-15T09:20:43.929129+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionview-6.0.3.1/lib/action_view/rendering.rb:117:in `block in _render_template'
2021-02-15T09:20:43.929130+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionview-6.0.3.1/lib/action_view/base.rb:304:in `in_rendering_context'
2021-02-15T09:20:43.929130+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionview-6.0.3.1/lib/action_view/rendering.rb:116:in `_render_template'
2021-02-15T09:20:43.929131+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.1/lib/action_controller/metal/streaming.rb:218:in `_render_template'
2021-02-15T09:20:43.929131+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionview-6.0.3.1/lib/action_view/rendering.rb:103:in `render_to_body'
2021-02-15T09:20:43.929131+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.1/lib/action_controller/metal/rendering.rb:52:in `render_to_body'
2021-02-15T09:20:43.929132+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.1/lib/action_controller/metal/renderers.rb:142:in `render_to_body'
2021-02-15T09:20:43.929132+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.1/lib/abstract_controller/rendering.rb:25:in `render'
2021-02-15T09:20:43.929133+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.1/lib/action_controller/metal/rendering.rb:36:in `render'
2021-02-15T09:20:43.929133+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.1/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
2021-02-15T09:20:43.929133+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.1/lib/active_support/core_ext/benchmark.rb:14:in `block in ms'
2021-02-15T09:20:43.929135+00:00 app[web.1]: /app/vendor/ruby-2.7.2/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
2021-02-15T09:20:43.929135+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.1/lib/active_support/core_ext/benchmark.rb:14:in `ms'
2021-02-15T09:20:43.929136+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.1/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
2021-02-15T09:20:43.929136+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.1/lib/action_controller/metal/instrumentation.rb:84:in `cleanup_view_runtime'
2021-02-15T09:20:43.929137+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.1/lib/active_record/railties/controller_runtime.rb:34:in `cleanup_view_runtime'
2021-02-15T09:20:43.929137+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.1/lib/action_controller/metal/instrumentation.rb:43:in `render'
2021-02-15T09:20:43.929138+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.1/lib/action_controller/metal/implicit_render.rb:35:in `default_render'
2021-02-15T09:20:43.929138+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.1/lib/action_controller/metal/basic_implicit_render.rb:6:in `block in send_action'
2021-02-15T09:20:43.929138+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.1/lib/action_controller/metal/basic_implicit_render.rb:6:in `tap'
2021-02-15T09:20:43.929139+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.1/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
2021-02-15T09:20:43.929139+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.1/lib/abstract_controller/base.rb:195:in `process_action'
2021-02-15T09:20:43.929140+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.1/lib/action_controller/metal/rendering.rb:30:in `process_action'
2021-02-15T09:20:43.929140+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.1/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
2021-02-15T09:20:43.929140+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:112:in `block in run_callbacks'
2021-02-15T09:20:43.929141+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/sentry-raven-3.0.0/lib/raven/integrations/rails/controller_transaction.rb:7:in `block in included'
2021-02-15T09:20:43.929141+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:121:in `instance_exec'
2021-02-15T09:20:43.929146+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
2021-02-15T09:20:43.929146+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:139:in `run_callbacks'
2021-02-15T09:20:43.929147+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.1/lib/abstract_controller/callbacks.rb:41:in `process_action'
2021-02-15T09:20:43.929147+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.1/lib/action_controller/metal/rescue.rb:22:in `process_action'
2021-02-15T09:20:43.929148+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.1/lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
2021-02-15T09:20:43.929148+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.1/lib/active_support/notifications.rb:180:in `block in instrument'
2021-02-15T09:20:43.929148+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
2021-02-15T09:20:43.929149+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.1/lib/active_support/notifications.rb:180:in `instrument'
2021-02-15T09:20:43.929149+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.1/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
2021-02-15T09:20:43.929150+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.1/lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
2021-02-15T09:20:43.929150+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.1/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
2021-02-15T09:20:43.929151+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.1/lib/abstract_controller/base.rb:136:in `process'
2021-02-15T09:20:43.929151+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionview-6.0.3.1/lib/action_view/rendering.rb:39:in `process'
2021-02-15T09:20:43.929151+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.1/lib/action_controller/metal.rb:190:in `dispatch'
2021-02-15T09:20:43.929152+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.1/lib/action_controller/metal.rb:254:in `dispatch'
2021-02-15T09:20:43.929152+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.1/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
2021-02-15T09:20:43.929152+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.1/lib/action_dispatch/routing/route_set.rb:33:in `serve'
2021-02-15T09:20:43.929153+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.1/lib/action_dispatch/journey/router.rb:49:in `block in serve'
2021-02-15T09:20:43.929153+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.1/lib/action_dispatch/journey/router.rb:32:in `each'
2021-02-15T09:20:43.929153+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.1/lib/action_dispatch/journey/router.rb:32:in `serve'
2021-02-15T09:20:43.929154+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.1/lib/action_dispatch/routing/route_set.rb:834:in `call'
2021-02-15T09:20:43.929154+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:192:in `call!'
2021-02-15T09:20:43.929155+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:169:in `call'
2021-02-15T09:20:43.929155+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/omniauth-1.9.1/lib/omniauth/builder.rb:45:in `call'
2021-02-15T09:20:43.929155+00:00 app[web.1]: /app/app/middlewares/rescue_from_invalid_authenticity_token.rb:8:in `call'
2021-02-15T09:20:43.929156+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'
2021-02-15T09:20:43.929156+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
2021-02-15T09:20:43.929157+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/conditional_get.rb:27:in `call'
2021-02-15T09:20:43.929157+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
2021-02-15T09:20:43.929157+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.1/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
2021-02-15T09:20:43.929158+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
2021-02-15T09:20:43.929158+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
2021-02-15T09:20:43.929158+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/cookies.rb:648:in `call'
2021-02-15T09:20:43.929159+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
2021-02-15T09:20:43.929159+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.1/lib/active_support/callbacks.rb:101:in `run_callbacks'
2021-02-15T09:20:43.929160+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
2021-02-15T09:20:43.929160+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
2021-02-15T09:20:43.929160+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
2021-02-15T09:20:43.929165+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
2021-02-15T09:20:43.929165+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.1/lib/rails/rack/logger.rb:37:in `call_app'
2021-02-15T09:20:43.929166+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.1/lib/rails/rack/logger.rb:26:in `block in call'
2021-02-15T09:20:43.929166+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.1/lib/active_support/tagged_logging.rb:80:in `block in tagged'
2021-02-15T09:20:43.929167+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.1/lib/active_support/tagged_logging.rb:28:in `tagged'
2021-02-15T09:20:43.929167+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.1/lib/active_support/tagged_logging.rb:80:in `tagged'
2021-02-15T09:20:43.929167+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.1/lib/rails/rack/logger.rb:26:in `call'
2021-02-15T09:20:43.929168+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
2021-02-15T09:20:43.929168+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/rack-timeout-0.6.0/lib/rack/timeout/core.rb:151:in `block in call'
2021-02-15T09:20:43.929169+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/rack-timeout-0.6.0/lib/rack/timeout/support/timeout.rb:19:in `timeout'
2021-02-15T09:20:43.929169+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/rack-timeout-0.6.0/lib/rack/timeout/core.rb:150:in `call'
2021-02-15T09:20:43.929169+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/request_id.rb:27:in `call'
2021-02-15T09:20:43.929170+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
2021-02-15T09:20:43.929170+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
2021-02-15T09:20:43.929171+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.1/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
2021-02-15T09:20:43.929171+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
2021-02-15T09:20:43.929171+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/static.rb:126:in `call'
2021-02-15T09:20:43.929172+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
2021-02-15T09:20:43.929172+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.1/lib/action_dispatch/middleware/host_authorization.rb:76:in `call'
2021-02-15T09:20:43.929172+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/sentry-raven-3.0.0/lib/raven/integrations/rack.rb:51:in `call'
2021-02-15T09:20:43.929173+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.1/lib/rails/engine.rb:527:in `call'
2021-02-15T09:20:43.929173+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/puma-4.3.5/lib/puma/configuration.rb:228:in `call'
2021-02-15T09:20:43.929174+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/puma-4.3.5/lib/puma/server.rb:713:in `handle_request'
2021-02-15T09:20:43.929174+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/puma-4.3.5/lib/puma/server.rb:472:in `process_client'
2021-02-15T09:20:43.929175+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/puma-4.3.5/lib/puma/server.rb:328:in `block in run'
2021-02-15T09:20:43.929175+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/puma-4.3.5/lib/puma/thread_pool.rb:134:in `block in spawn_thread'
2021-02-15T09:20:43.929562+00:00 app[web.1]: I, [2021-02-15T09:20:43.929501 #10]  INFO -- : [1cf11d12-e77e-4e39-ba47-d597e42e4789]   Rendering errors/error_500.html.erb within layouts/application
2021-02-15T09:20:43.929768+00:00 app[web.1]: I, [2021-02-15T09:20:43.929696 #10]  INFO -- : [1cf11d12-e77e-4e39-ba47-d597e42e4789]   Rendered errors/error_500.html.erb within layouts/application (Duration: 0.1ms | Allocations: 4)
```

**Comment by jacopen** [comment]
↑はHeroku log。捨てメアドで試しても確かに再現する。
ただし、同じアカウントを使っても開発環境だと起きていない。

**Comment by jacopen** [comment]
エラーの原因としてはこれ。
```
2021-02-15T09:44:44.274018+00:00 app[web.1]: E, [2021-02-15T09:44:44.273932 #10] ERROR -- : [ab606e9a-d204-4798-8828-b1b293fb92cf] Rendering 500 with exception: undefined method `avatar_url' for nil:NilClass
2021-02-15T09:44:44.274263+00:00 app[web.1]: E, [2021-02-15T09:44:44.274074 #10] ERROR -- : [ab606e9a-d204-4798-8828-b1b293fb92cf] /app/app/views/speaker_dashboard/speakers/_form.html.erb:43:in `block in _app_views_speaker_dashboard_speakers__form_html_erb__2313813606917588312_335440'
```

しかし、該当コードを見る限り `@speaker` が無い限りは `@speaker.avatar_url` は評価されないように思うんだが、実際には評価されてしまっている。つまり @speakerに値が入ってしまっていると考えられる。なじぇ。
https://github.com/cloudnativedaysjp/dreamkast/blob/main/app/views/speaker_dashboard/speakers/_form.html.erb#L43

**Comment by jacopen** [comment]
/:event/speakers/entry は speaker_dashboard/speakers#new にルーティングされる。
```
                       speakers_entry GET    /:event/speakers/entry(.:format)                                                         speaker_dashboard/speakers#new
```

コードを読む限りでは、@speakerがセットされる場所はないように思うのだが、何故･･･
実際ここのロジックが間違っているのであれば開発環境でも出るはず・・・何故・・・
https://github.com/cloudnativedaysjp/dreamkast/blob/main/app/controllers/speaker_dashboard/speakers_controller.rb#L7-L18

**Comment by jacopen** [comment]
こちら解決したと思うのでクローズ
