### ISSUE TITLE
動画のアップロード後にエラーが出てしまう

### ISSUE THREAD

**Issue by jacopen** [cloudnativedaysjp/dreamkast#531]
Slackからの連絡

https://cloudnativedays.slack.com/archives/C8UHQTDGB/p1614323308003100

初回申告時はファイル名のみがDBに書き込まれ、S3にデータが無い状態だった。

その後再アップロードしてもらったところ、ファイルは正しくアップロードされているがエラーが出たものと思われる？

**Comment by jacopen** [comment]
後者のエラーについてはSESでエラーが出るケースが過去にもあったため、その可能性がある。
前者は不明･･･

後者はメール送信をsidekiqなどによる非同期送信にするなど修正が必要。前者はログチェック要

**Comment by jacopen** [comment]
また別件でアップロード出来ない報告を受けた
https://cloudnativedays.slack.com/archives/C015CN1PQ06/p1614328856340400

今日になって突然頻発しているので、もしかすると複数インスタンスにしたのが影響しているかもしれない

**Comment by jacopen** [comment]
現時点でAdminページがエラーを吐く。アップロード周りで入れられたデータが何かおかしい

```
I, [2021-02-26T08:46:13.229441 #168]  INFO -- : [ddaf6eee-fe17-4a4e-867e-c260f1872a50]   Rendered admin/talks/index.html.erb within layouts/application (Duration: 683.4ms | Allocations: 107590)
E, [2021-02-26T08:46:13.229673 #168] ERROR -- : [ddaf6eee-fe17-4a4e-867e-c260f1872a50] Rendering 500 with exception: 783: unexpected token at ''
E, [2021-02-26T08:46:13.230068 #168] ERROR -- : [ddaf6eee-fe17-4a4e-867e-c260f1872a50] /usr/local/lib/ruby/2.7.0/json/common.rb:156:in `parse'
/usr/local/lib/ruby/2.7.0/json/common.rb:156:in `parse'
/usr/local/bundle/gems/shrine-3.3.0/lib/shrine/plugins/column.rb:95:in `load'
/usr/local/bundle/gems/shrine-3.3.0/lib/shrine/plugins/column.rb:79:in `deserialize_column'
/usr/local/bundle/gems/shrine-3.3.0/lib/shrine/plugins/column.rb:42:in `load_column'
/usr/local/bundle/gems/shrine-3.3.0/lib/shrine/plugins/entity.rb:139:in `read'
/usr/local/bundle/gems/shrine-3.3.0/lib/shrine/plugins/model.rb:101:in `load_model'
/usr/local/bundle/gems/shrine-3.3.0/lib/shrine/plugins/model.rb:63:in `attacher'
/usr/local/bundle/gems/shrine-3.3.0/lib/shrine/plugins/entity.rb:50:in `block in define_entity_methods'
/usr/local/bundle/gems/shrine-3.3.0/lib/shrine/plugins/entity.rb:40:in `block in define_entity_methods'
/app/app/views/admin/talks/index.html.erb:78:in `block (2 levels) in _app_views_admin_talks_index_html_erb___2925061568098725494_88000'
/usr/local/bundle/gems/activerecord-6.0.3.1/lib/active_record/relation/delegation.rb:87:in `each'
/usr/local/bundle/gems/activerecord-6.0.3.1/lib/active_record/relation/delegation.rb:87:in `each'
/app/app/views/admin/talks/index.html.erb:60:in `block in _app_views_admin_talks_index_html_erb___2925061568098725494_88000'
```

**Comment by jacopen** [comment]
仮説だけど、これアップロード開始時に繋がっていたインスタンスと、終了時のインスタンスが異なっていたら何が起きる・・・？

**Comment by jacopen** [comment]
1インスタンスにして600MB程度のファイルをアップロードしたが特に問題は起きなかった。
Stagingで複数インスタンスにして試してみようかな

**Comment by takaishi** [comment]
こっちは解消済みという認識でOK？

**Comment by jacopen** [comment]
ここで起きている前者は #521 と思われるのでそちらで対処
SESの件は解消したのでこちらはクローズ
