### ISSUE TITLE
コンテナ起動時にassets:precompileしなくてもよくしたい

### ISSUE THREAD

**Issue by takaishi** [cloudnativedaysjp/dreamkast#587]

**Comment by ShotaKitazawa** [comment]
コンテナ起動時に assets:precompile してるところはここ

https://github.com/cloudnativedaysjp/dreamkast/blob/80d8780fa6c0a997e25fd05525d57a75ac8a1cfe/entrypoint.sh#L2

**Comment by ShotaKitazawa** [comment]
イメージビルド時にこのへんで asset compile してるのになぜコンテナ起動時にも必要なんだ・・・？ という状態

https://github.com/cloudnativedaysjp/dreamkast/blob/80d8780fa6c0a997e25fd05525d57a75ac8a1cfe/Dockerfile#L11-L27

**Comment by ShotaKitazawa** [comment]
以下のハッシュで docker run して、その中で assets:precompile → 失敗

https://github.com/cloudnativedaysjp/dreamkast/blob/80d8780fa6c0a997e25fd05525d57a75ac8a1cfe/Dockerfile#L25 

```
root@289c97768cab:/app# bundle exec rails assets:precompile
I, [2021-03-09T12:12:48.719422 #9]  INFO -- sentry: ** [Raven] Raven 3.0.0 configured not to capture errors: DSN not set
["/app/db/fixtures", "/app/db/fixtures/development"]
yarn install v1.22.4
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.39s.
yarn install v1.22.4
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.34s.
I, [2021-03-09T12:12:50.991693 #9]  INFO -- : Writing /app/public/assets/manifest-b4bf6e57a53c2bdb55b8998cc94cd00883793c1c37c5e5aea3ef6749b4f6d92b.js
I, [2021-03-09T12:12:50.991974 #9]  INFO -- : Writing /app/public/assets/manifest-b4bf6e57a53c2bdb55b8998cc94cd00883793c1c37c5e5aea3ef6749b4f6d92b.js.gz
I, [2021-03-09T12:12:50.992099 #9]  INFO -- : Writing /app/public/assets/GitHub-Mark-64px-3033f7d9971fd5e41f305d793b4f76a715c2d306f8c59214a22adec6e1cb8c8c.png
I, [2021-03-09T12:12:50.992519 #9]  INFO -- : Writing /app/public/assets/Twitter_Social_Icon_Circle_Color-7e96549282e3bbf3a5757d6a9f3de43abaa7b753caac6ae20fe26dad2eeb94a9.png
I, [2021-03-09T12:12:50.993091 #9]  INFO -- : Writing /app/public/assets/cndo2021/header_logo-46665a9af66deb90e2bd903944fbe70fc3e20a713e1ff0512f2bfbd2b0751718.png
I, [2021-03-09T12:12:50.993567 #9]  INFO -- : Writing /app/public/assets/cndo2021/how_to_upload_1-153176fe656b01785af6925c2d10f3076ccc9b8548ae8e187786797d48e41dee.png
I, [2021-03-09T12:12:50.994138 #9]  INFO -- : Writing /app/public/assets/cndo2021/how_to_upload_2-5b411001541bd32bf991fc555bc24eef9f43c7242c62c9711762deec3e868402.png
I, [2021-03-09T12:12:50.994489 #9]  INFO -- : Writing /app/public/assets/cndo2021/masthead-1c14d0789041a4d53afbf42cd465b34932ffb6252fe6850ecd1ea2773c0f10f7.png
I, [2021-03-09T12:12:50.997538 #9]  INFO -- : Writing /app/public/assets/cndo2021/trademark-806d0b759527f14238a7bfb1bf9342a9059bf3e2bd5409224c7a201e2b796b7c.png
I, [2021-03-09T12:12:50.998017 #9]  INFO -- : Writing /app/public/assets/cndt2020/header_logo-fb474e8e4e00e7768bf33a79fb922692e6853e424a801fb52cf90180afb679fa.png
I, [2021-03-09T12:12:50.998315 #9]  INFO -- : Writing /app/public/assets/cndt2020/trademark-493492ac00db6dd6e1bf19ec6c8f798e55574f1fa820aed2cac123bc4a502511.png
I, [2021-03-09T12:12:50.998715 #9]  INFO -- : Writing /app/public/assets/contents/discussion_board-b86bbffa252ef70c508b21911d19a3eb8861caac0cb427cb1b8b9aa9be665d88.png
I, [2021-03-09T12:12:50.999023 #9]  INFO -- : Writing /app/public/assets/contents/discussion_board_howto-a1e15823f252dde6dd53d73722eda0fd8401d919fc143fc9d9852f1e291f4448.png
I, [2021-03-09T12:12:50.999360 #9]  INFO -- : Writing /app/public/assets/contents/kontest-3bc89d70832e393db1816b2efba042a98eee3e804cc5c19f060740eb1d071b95.png
I, [2021-03-09T12:12:50.999798 #9]  INFO -- : Writing /app/public/assets/dummy-90a85fa80bf3316e993e9b5b6b8a20ab0e0c7c584a8b8a14c265e2beeaab6703.png
I, [2021-03-09T12:12:51.000130 #9]  INFO -- : Writing /app/public/assets/favicon-54ba83b188a78702c2db24ae0b0c3d4e0e9ee466b0715a4e61b56fdec9ad45d2.ico
I, [2021-03-09T12:12:51.000410 #9]  INFO -- : Writing /app/public/assets/favicon-54ba83b188a78702c2db24ae0b0c3d4e0e9ee466b0715a4e61b56fdec9ad45d2.ico.gz
I, [2021-03-09T12:12:51.000597 #9]  INFO -- : Writing /app/public/assets/pdf-c9a3ea5e86c4c204c71932cd0355ef7584ebb867709a4091e3122a88946fd128.svg
I, [2021-03-09T12:12:51.000906 #9]  INFO -- : Writing /app/public/assets/pdf-c9a3ea5e86c4c204c71932cd0355ef7584ebb867709a4091e3122a88946fd128.svg.gz
I, [2021-03-09T12:12:51.001125 #9]  INFO -- : Writing /app/public/assets/sponsors/cndo2021/acquia-195ca43ca4f2139c4172b2642e7578228b6439546b8a18a071300af507a2431e.png
I, [2021-03-09T12:12:51.001604 #9]  INFO -- : Writing /app/public/assets/sponsors/cndo2021/circleci-45f60a7083923773bd7b50669a1c6955873de650b72093a013393421eebaf544.png
I, [2021-03-09T12:12:51.002127 #9]  INFO -- : Writing /app/public/assets/sponsors/cndo2021/cloudnative-b5d9b2d7226ecacc33ff8f5a963e6dcf8e6ea85472475c62f7513d195d91f112.png
I, [2021-03-09T12:12:51.002659 #9]  INFO -- : Writing /app/public/assets/sponsors/cndo2021/datadog-096ef7c840cf4a11c1e1564b7a4eed854f0612939056192027f7d8f2244f0eb8.png
I, [2021-03-09T12:12:51.003162 #9]  INFO -- : Writing /app/public/assets/sponsors/cndo2021/gmo-f099a56f6d0375d614794acc3f324633055f80b870d4847ec082d51027804e41.png
I, [2021-03-09T12:12:51.003661 #9]  INFO -- : Writing /app/public/assets/sponsors/cndo2021/jfrog-7ae143a8dd810fbb0a18dce239cc822771ffcb58e2905df6b73974f9486df297.png
I, [2021-03-09T12:12:51.003979 #9]  INFO -- : Writing /app/public/assets/sponsors/cndo2021/legalforce-3e36541e3bbb84e606859c5f4d9ff71b01ef38753d304a25f6efde5b9d1941c7.png
I, [2021-03-09T12:12:51.004328 #9]  INFO -- : Writing /app/public/assets/sponsors/cndo2021/lf-1fdd7af055abf3b83aad8dfce9907422854b2f8eac04a148b3ed887e4504d211.png
I, [2021-03-09T12:12:51.004679 #9]  INFO -- : Writing /app/public/assets/sponsors/cndo2021/lf.png:Zone-55b34e1c3c99dad47937a530953cf4f02e20d83da114bec6296c2bcfa0357537.Identifier
I, [2021-03-09T12:12:51.004849 #9]  INFO -- : Writing /app/public/assets/sponsors/cndo2021/line-775254164251367b7b6a12811b2d84e7aa34287d14f1db1ac95d7540e41b4298.png
I, [2021-03-09T12:12:51.005255 #9]  INFO -- : Writing /app/public/assets/sponsors/cndo2021/lpi-5db8f25d5a941315667f1117a42f76375521053bf4ded1541d9c94c49f02e778.png
I, [2021-03-09T12:12:51.005646 #9]  INFO -- : Writing /app/public/assets/sponsors/cndo2021/lpi.png:Zone-cbdb7caa9a09c195ceb7efd45d1017ccd9070d10c55222305ed06f72939edcd6.Identifier
I, [2021-03-09T12:12:51.005820 #9]  INFO -- : Writing /app/public/assets/sponsors/cndo2021/microsoft-674c7c51e941ecfc7d580c74c3e1fd1eac72ed298cf437edf3cb0a6eeda36cdd.png
I, [2021-03-09T12:12:51.006149 #9]  INFO -- : Writing /app/public/assets/sponsors/cndo2021/mirantis-39b6466a4529b2a6de9aa43318b8e1842d02b597f489b5104a3a2d008bfdaec1.png
I, [2021-03-09T12:12:51.006520 #9]  INFO -- : Writing /app/public/assets/sponsors/cndo2021/newrelic-5f8a04a8de07c26e934750112593aa0d76bf585d92426ca4561f59a0ada8b075.png
I, [2021-03-09T12:12:51.006961 #9]  INFO -- : Writing /app/public/assets/sponsors/cndo2021/nginx-d221a66b9f43a838c82222b8bd2eeecfaab6201d3d027937009c06ace218d3a1.png
I, [2021-03-09T12:12:51.007278 #9]  INFO -- : Writing /app/public/assets/sponsors/cndo2021/plaid-98b0910da41ee517eb0cf4a16a46049f57c964f706a308948c53b45be14adba6.png
I, [2021-03-09T12:12:51.007661 #9]  INFO -- : Writing /app/public/assets/sponsors/cndo2021/redhat-56ad8696f1c14e0b53144cbc8f79193d62576ce4457062892a64091e131e0fb5.png
I, [2021-03-09T12:12:51.008006 #9]  INFO -- : Writing /app/public/assets/sponsors/cndo2021/scsk-71140989553fb68a2dc699e5b4e6cbb51b5d4a309d32fc7d77fe1a7767923593.png
I, [2021-03-09T12:12:51.008347 #9]  INFO -- : Writing /app/public/assets/sponsors/cndo2021/suse-d3d6e7d9c872aa96044dfdb824cea2d44cb8ded0a63c43be2886998df083655a.png
I, [2021-03-09T12:12:51.008674 #9]  INFO -- : Writing /app/public/assets/sponsors/cndo2021/vmware-c34478e2c2f87edaf37424b75abd8110f690d5aedd1d358ca009c15d6b0652b5.png
I, [2021-03-09T12:12:51.008975 #9]  INFO -- : Writing /app/public/assets/sponsors/cndt2020/canonical-57aa9ca75106f4bf356bf75b9f1e22693f960d3d0e52df99da69c92079f17d3a.png
I, [2021-03-09T12:12:51.009267 #9]  INFO -- : Writing /app/public/assets/sponsors/cndt2020/casareal-3937ba0463a95424d73711be21a1cc846d6c5f1920e161bb1e010852e9dc7ef3.png
I, [2021-03-09T12:12:51.009592 #9]  INFO -- : Writing /app/public/assets/sponsors/cndt2020/circleci-45f60a7083923773bd7b50669a1c6955873de650b72093a013393421eebaf544.png
I, [2021-03-09T12:12:51.009945 #9]  INFO -- : Writing /app/public/assets/sponsors/cndt2020/cncf-4d062c3b9ebe8439586f9f6aa7c5bc7cd1526298eb90f516ffeec5aedc7ddd58.jpg
I, [2021-03-09T12:12:51.011265 #9]  INFO -- : Writing /app/public/assets/sponsors/cndt2020/cyberagent-f0980b204e2dd4cfa1867e16e3a72412c5e2e13557e1037bc48f7e85784269e2.png
I, [2021-03-09T12:12:51.011490 #9]  INFO -- : Writing /app/public/assets/sponsors/cndt2020/diverta-718160688f02c24f5e217a9420a468b6b97e2d3af0f025b4b994ac415271f725.png
I, [2021-03-09T12:12:51.011864 #9]  INFO -- : Writing /app/public/assets/sponsors/cndt2020/elastic-e79251183734c3fd340cc333311d9f85e79f3947ee2adc8b98702a8c6eefec19.png
I, [2021-03-09T12:12:51.012304 #9]  INFO -- : Writing /app/public/assets/sponsors/cndt2020/f5-647d757ba12a6f556db7d2c0eb4fbf844dfa5921c4312a7e77b4dd7c8db6a1f5.jpg
I, [2021-03-09T12:12:51.012810 #9]  INFO -- : Writing /app/public/assets/sponsors/cndt2020/fujitsu-45d79cc0a804fde4e9496497224bf32893461d2e0aebb289fafcda17f784a70c.png
I, [2021-03-09T12:12:51.013193 #9]  INFO -- : Writing /app/public/assets/sponsors/cndt2020/gmo-pepabo-8df29fdec8c17d0cb666d4c117e61e96c98f61eac0a80a8088477f25296e835a.png
I, [2021-03-09T12:12:51.013678 #9]  INFO -- : Writing /app/public/assets/sponsors/cndt2020/google-a2501d5f96001d75c7302dd12075e97083439798dfaaa4af39d5f94fd64e8637.png
I, [2021-03-09T12:12:51.014152 #9]  INFO -- : Writing /app/public/assets/sponsors/cndt2020/hatena-fd07d8a04ca6b83220cf4c7903c5adede9752d7e2f08e32839a181c08b40672e.png
I, [2021-03-09T12:12:51.014645 #9]  INFO -- : Writing /app/public/assets/sponsors/cndt2020/ibm-753e1a24fc2a526990a88918c25e0c71fc9f74c72b9e2875abdf12e9642958dd.jpg
I, [2021-03-09T12:12:51.015087 #9]  INFO -- : Writing /app/public/assets/sponsors/cndt2020/jfrog-7ae143a8dd810fbb0a18dce239cc822771ffcb58e2905df6b73974f9486df297.png
I, [2021-03-09T12:12:51.015553 #9]  INFO -- : Writing /app/public/assets/sponsors/cndt2020/legalforce-3e36541e3bbb84e606859c5f4d9ff71b01ef38753d304a25f6efde5b9d1941c7.png
I, [2021-03-09T12:12:51.016020 #9]  INFO -- : Writing /app/public/assets/sponsors/cndt2020/microsoft-674c7c51e941ecfc7d580c74c3e1fd1eac72ed298cf437edf3cb0a6eeda36cdd.png
I, [2021-03-09T12:12:51.016488 #9]  INFO -- : Writing /app/public/assets/sponsors/cndt2020/mirantis-39b6466a4529b2a6de9aa43318b8e1842d02b597f489b5104a3a2d008bfdaec1.png
I, [2021-03-09T12:12:51.016709 #9]  INFO -- : Writing /app/public/assets/sponsors/cndt2020/nec-1d49e0e9b2217eaf94404d14b8f9d02471977f7d80e99d86bfa1a9fa0e89b6a7.png
I, [2021-03-09T12:12:51.016881 #9]  INFO -- : Writing /app/public/assets/sponsors/cndt2020/newrelic-5f8a04a8de07c26e934750112593aa0d76bf585d92426ca4561f59a0ada8b075.png
I, [2021-03-09T12:12:51.017716 #9]  INFO -- : Writing /app/public/assets/sponsors/cndt2020/nttdata-3a716f7a4cb7daa5333b16fb354f158e85fe71e5d01c11e446e656f5042ef6b3.png
I, [2021-03-09T12:12:51.018240 #9]  INFO -- : Writing /app/public/assets/sponsors/cndt2020/oracle-13c5967fcbc300d394d7a6a407613abdfd6cf0ded0ad6f4f7f03214fd469179e.png
I, [2021-03-09T12:12:51.018708 #9]  INFO -- : Writing /app/public/assets/sponsors/cndt2020/plaid-98b0910da41ee517eb0cf4a16a46049f57c964f706a308948c53b45be14adba6.png
I, [2021-03-09T12:12:51.019019 #9]  INFO -- : Writing /app/public/assets/sponsors/cndt2020/rancherlabs-6bf1a63f159d1ebf14609f9761a249f4cd938d9dcd1b63c730c577916a96b04b.png
I, [2021-03-09T12:12:51.019455 #9]  INFO -- : Writing /app/public/assets/sponsors/cndt2020/redhat-56ad8696f1c14e0b53144cbc8f79193d62576ce4457062892a64091e131e0fb5.png
I, [2021-03-09T12:12:51.019954 #9]  INFO -- : Writing /app/public/assets/sponsors/cndt2020/sios-7142ad57a4601d840b4909ccfc0282ae7a04bbe4353cd9346f1188b1b9183939.png
I, [2021-03-09T12:12:51.020458 #9]  INFO -- : Writing /app/public/assets/sponsors/cndt2020/suse-7e9b2b5dd192fbcd499246fcfd91c72e8e20896e3dd95b7ef62bf9d22859004e.png
I, [2021-03-09T12:12:51.020957 #9]  INFO -- : Writing /app/public/assets/sponsors/cndt2020/sysdig-58afc9366383fbd7c45db4843d2dcfba7626bcf3310f80ab55f8e63ecc5cf0e0.png
I, [2021-03-09T12:12:51.021537 #9]  INFO -- : Writing /app/public/assets/sponsors/cndt2020/vmware-c34478e2c2f87edaf37424b75abd8110f690d5aedd1d358ca009c15d6b0652b5.png
I, [2021-03-09T12:12:51.021880 #9]  INFO -- : Writing /app/public/assets/trademark-493492ac00db6dd6e1bf19ec6c8f798e55574f1fa820aed2cac123bc4a502511.png
I, [2021-03-09T12:12:51.022302 #9]  INFO -- : Writing /app/public/assets/application-b324c44f04a0d0da658824105489a2676d49df561c3d06723770321fd441977c.css
I, [2021-03-09T12:12:51.022472 #9]  INFO -- : Writing /app/public/assets/application-b324c44f04a0d0da658824105489a2676d49df561c3d06723770321fd441977c.css.gz
I, [2021-03-09T12:12:51.022685 #9]  INFO -- : Writing /app/public/assets/contents-04024382391bb910584145d8113cf35ef376b55d125bb4516cebeb14ce788597.css
I, [2021-03-09T12:12:51.022989 #9]  INFO -- : Writing /app/public/assets/contents-04024382391bb910584145d8113cf35ef376b55d125bb4516cebeb14ce788597.css.gz
I, [2021-03-09T12:12:51.023182 #9]  INFO -- : Writing /app/public/assets/custom-04024382391bb910584145d8113cf35ef376b55d125bb4516cebeb14ce788597.css
I, [2021-03-09T12:12:51.023433 #9]  INFO -- : Writing /app/public/assets/custom-04024382391bb910584145d8113cf35ef376b55d125bb4516cebeb14ce788597.css.gz
I, [2021-03-09T12:12:51.023620 #9]  INFO -- : Writing /app/public/assets/speakers-04024382391bb910584145d8113cf35ef376b55d125bb4516cebeb14ce788597.css
I, [2021-03-09T12:12:51.023859 #9]  INFO -- : Writing /app/public/assets/speakers-04024382391bb910584145d8113cf35ef376b55d125bb4516cebeb14ce788597.css.gz
I, [2021-03-09T12:12:51.024135 #9]  INFO -- : Writing /app/public/assets/talks-04024382391bb910584145d8113cf35ef376b55d125bb4516cebeb14ce788597.css
I, [2021-03-09T12:12:51.024433 #9]  INFO -- : Writing /app/public/assets/talks-04024382391bb910584145d8113cf35ef376b55d125bb4516cebeb14ce788597.css.gz
Compiling...





Compilation failed:
Hash: 5a88021af4304a3f58c3
Version: webpack 4.43.0
Time: 20183ms
Built at: 03/09/2021 12:13:12 PM
 84 assets
Entrypoint admin = js/admin-2f3fd358bf6a04eb0630.js js/admin-2f3fd358bf6a04eb0630.js.map
Entrypoint admin/tracks/consumer = js/admin/tracks/consumer-3c1d2a6a40d11856ab8e.js js/admin/tracks/consumer-3c1d2a6a40d11856ab8e.js.map
Entrypoint admin/tracks/index = js/admin/tracks/index-d8fe77d474101b6e2c4c.js js/admin/tracks/index-d8fe77d474101b6e2c4c.js.map
Entrypoint admin/tracks/tracks_channel = js/admin/tracks/tracks_channel-ba8fb87f90482fd7ab2d.js js/admin/tracks/tracks_channel-ba8fb87f90482fd7ab2d.js.map
Entrypoint admin/tracks/tracks_control = js/admin/tracks/tracks_control-d0f744ab4e051a915037.js js/admin/tracks/tracks_control-d0f744ab4e051a915037.js.map
Entrypoint application = js/application-b9b5c8e53bdfccef5bab.js js/application-b9b5c8e53bdfccef5bab.js.map
Entrypoint booth = js/booth-b085054cd6e04e006a0b.js js/booth-b085054cd6e04e006a0b.js.map
Entrypoint bootstrap_custom = js/bootstrap_custom-a1ccbb1b5d81501786ad.js js/bootstrap_custom-a1ccbb1b5d81501786ad.js.map
Entrypoint bootstrap-table-filter-control = js/bootstrap-table-filter-control-5a8e49a76a889fe1c05e.js js/bootstrap-table-filter-control-5a8e49a76a889fe1c05e.js.map
Entrypoint bootstrap-table = js/bootstrap-table-b101a2970828ecbfaf37.js js/bootstrap-table-b101a2970828ecbfaf37.js.map
Entrypoint chat/chat_channel = js/chat/chat_channel-3fccbd0c81aedb5bedbc.js js/chat/chat_channel-3fccbd0c81aedb5bedbc.js.map
Entrypoint chat/consumer = js/chat/consumer-ff52ff0830e309719f39.js js/chat/consumer-ff52ff0830e309719f39.js.map
Entrypoint chat/index = js/chat/index-5cb450c19584eb21d7e2.js js/chat/index-5cb450c19584eb21d7e2.js.map
Entrypoint cndo2021 = js/cndo2021-a68bb4948fb302619f57.js js/cndo2021-a68bb4948fb302619f57.js.map
Entrypoint conference_form = js/conference_form-d08c697204d5b1908d5a.js js/conference_form-d08c697204d5b1908d5a.js.map
Entrypoint contents = js/contents-3a1a8f97b19ab0764155.js js/contents-3a1a8f97b19ab0764155.js.map
Entrypoint jquery = js/jquery-a52318800e94815dc321.js js/jquery-a52318800e94815dc321.js.map
Entrypoint message_box = js/message_box-7e618dd050e33162647f.js js/message_box-7e618dd050e33162647f.js.map
Entrypoint scripts = js/scripts-f74c6b57dc6e44572f7e.js js/scripts-f74c6b57dc6e44572f7e.js.map
Entrypoint speaker_form = js/speaker_form-acb9a12e16d360e07d85.js js/speaker_form-acb9a12e16d360e07d85.js.map
Entrypoint sponsor_form = js/sponsor_form-8ba301f12eb0f2829909.js js/sponsor_form-8ba301f12eb0f2829909.js.map
Entrypoint talks = js/talks-b18a5828d7d5b3ca44ad.js js/talks-b18a5828d7d5b3ca44ad.js.map
Entrypoint timetable = js/timetable-e660cec43073792e6516.js js/timetable-e660cec43073792e6516.js.map
Entrypoint tracks/consumer = js/tracks/consumer-40b26425cd24e6d7700d.js js/tracks/consumer-40b26425cd24e6d7700d.js.map
Entrypoint tracks/index = js/tracks/index-cd79276de7d47950af12.js js/tracks/index-cd79276de7d47950af12.js.map
Entrypoint tracks/track_channel = js/tracks/track_channel-f29edd04a1205dd89fae.js js/tracks/track_channel-f29edd04a1205dd89fae.js.map
Entrypoint tracks/track_control = js/tracks/track_control-359f6eb397637de58567.js js/tracks/track_control-359f6eb397637de58567.js.map
Entrypoint tracks/waiting_channel = js/tracks/waiting_channel-0abd34be1720227eae03.js js/tracks/waiting_channel-0abd34be1720227eae03.js.map
Entrypoint utils = js/utils-a2a49da5c8539ef4e94f.js js/utils-a2a49da5c8539ef4e94f.js.map
Entrypoint video_uploader = js/video_uploader-db08123406543cc7cdbd.js js/video_uploader-db08123406543cc7cdbd.js.map
 [9] ./app/javascript/packs/tracks/consumer.js 259 bytes {23} {24} {25} {27} [built]
[14] ./app/javascript/packs/tracks/track_control.js 2.29 KiB {24} {25} {26} {27} [built]
[19] ./app/javascript/packs/admin/tracks/consumer.js 259 bytes {1} {2} {3} [built]
[20] ./app/javascript/packs/chat/consumer.js 259 bytes {10} {11} {12} [built]
[21] ./app/javascript/packs/admin.js 608 bytes {0} {5} {13} [built]
[22] ./app/javascript/packs/admin/tracks/tracks_control.js 715 bytes {2} {3} {4} [built]
[23] ./app/javascript/packs/bootstrap_custom.js 431 bytes {5} {9} {13} [built]
[35] ./app/javascript/packs/bootstrap-table.js 200 KiB {5} {7} {13} [built]
[36] ./app/javascript/packs/utils.js 64.5 KiB {5} {13} {28} [built]
[37] ./app/javascript/packs/bootstrap-table-filter-control.js 79.8 KiB {5} {8} {13} [built]
[38] ./app/javascript/packs/jquery.magnific-popup.min.js 19.9 KiB {5} {13} {16} [built]
[39] ./app/javascript/packs/scripts.js 1.75 KiB {5} {13} {18} [built]
[40] ./app/javascript/packs/talks.js 513 bytes {5} {13} {21} [built]
[41] ./app/javascript/packs/sponsor_form.js 1.14 KiB {5} {13} {20} [built]
[42] ./app/javascript/packs/conference_form.js 420 bytes {5} {13} {14} [built]
    + 155 hidden modules

ERROR in ./node_modules/@uppy/core/dist/style.css (./node_modules/css-loader/dist/cjs.js??ref--6-1!./node_modules/postcss-loader/src??ref--6-2!./node_modules/@uppy/core/dist/style.css)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: No PostCSS Config found in: /app
    at /app/node_modules/postcss-load-config/src/index.js:91:15
 @ ./node_modules/@uppy/core/dist/style.css 2:26-139
 @ ./app/javascript/packs/video_uploader.js

ERROR in ./node_modules/@uppy/dashboard/dist/style.css (./node_modules/css-loader/dist/cjs.js??ref--6-1!./node_modules/postcss-loader/src??ref--6-2!./node_modules/@uppy/dashboard/dist/style.css)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: No PostCSS Config found in: /app
    at /app/node_modules/postcss-load-config/src/index.js:91:15
 @ ./node_modules/@uppy/dashboard/dist/style.css 2:26-139
 @ ./app/javascript/packs/video_uploader.js

ERROR in ./app/javascript/stylesheets/cndo2021.scss (./node_modules/css-loader/dist/cjs.js??ref--7-1!./node_modules/postcss-loader/src??ref--7-2!./node_modules/sass-loader/dist/cjs.js??ref--7-3!./app/javascript/stylesheets/cndo2021.scss)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: No PostCSS Config found in: /app
    at /app/node_modules/postcss-load-config/src/index.js:91:15
 @ ./app/javascript/stylesheets/cndo2021.scss 2:26-225
 @ ./app/javascript/packs/cndo2021.js

ERROR in ./app/javascript/stylesheets/application.scss (./node_modules/css-loader/dist/cjs.js??ref--7-1!./node_modules/postcss-loader/src??ref--7-2!./node_modules/sass-loader/dist/cjs.js??ref--7-3!./app/javascript/stylesheets/application.scss)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: No PostCSS Config found in: /app
    at /app/node_modules/postcss-load-config/src/index.js:91:15
 @ ./app/javascript/stylesheets/application.scss 2:26-228
 @ ./app/javascript/packs/application.js


Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
```

**Comment by ShotaKitazawa** [comment]
---
@ShotaKitazawa の頭の中共有: rails 何も分からんなので、 `rake webpacker:install && rake webpacker:compile` と `bundle exec rails assets:precompile` の違いを調べ、なんでコンテナ内で `bundle exec rails assets:precompile` するのは失敗するのかを調べる。

**Comment by ShotaKitazawa** [comment]
https://qiita.com/magaya0403/items/ce454ad6567f748051c0 を試した結果、失敗 (https://github.com/cloudnativedaysjp/dreamkast/issues/587#issuecomment-793926188 と同じエラー)

**Comment by ShotaKitazawa** [comment]
`rails webpacker:install && rails webpacker:compile` は webpacker を利用した precompile だが、 `bundle exec rails assets:precompile` は Sprockets を使ってそう？

**Comment by ShotaKitazawa** [comment]
解決までの道は2通りありそう

* ① Dockerfile 側の assets compile Stage にて、 `bundle exec rails assets:precompile` の実行を成功させる
* ② `rails webpacker:install && rails webpacker:compile` の実行後に curl を叩いて 500 エラーが出ないようにする

**Comment by ShotaKitazawa** [comment]
https://github.com/cloudnativedaysjp/dreamkast/issues/587#issuecomment-793924328

上記 500 エラーのエラーメッセージが `Sprockets::Rails::Helper::AssetNotFound in Home#show` であることから、 `rails webpacker:install && rails webpacker:compile` だとそもそも Sprockets のための compile が実行されないからエラーが出てそう？

→ ① の方向性で調査したほうが良さげなのでそうします

**Comment by ShotaKitazawa** [comment]
https://github.com/cloudnativedaysjp/dreamkast/issues/587#issuecomment-793926188

> ERROR in ./app/javascript/stylesheets/application.scss (./node_modules/css-loader/dist/cjs.js??ref--7-1!./node_modules/postcss-loader/src??ref--7-2!./node_modules/sass-loader/dist/cjs.js??ref--7-3!./app/javascript/stylesheets/application.scss)
> Module build failed (from ./node_modules/postcss-loader/src/index.js):
> Error: No PostCSS Config found in: /app

より `COPY postcss.config.js .` を precompile Stage で実行したら、 `bundle exec rails assets:precompile` が実行できるようになった

**Comment by ShotaKitazawa** [comment]
![スクリーンショット 2021-03-10 4 04 40](https://user-images.githubusercontent.com/19530785/110523699-cd35f200-8155-11eb-9978-8647acccf4d0.png)
![スクリーンショット 2021-03-10 4 04 50](https://user-images.githubusercontent.com/19530785/110523705-ceffb580-8155-11eb-914d-ad8028254900.png)

**Comment by takaishi** [comment]
動いてるので完了！
