### ISSUE TITLE
[oke-py] dreamkastのローカル開発環境を構築する

### ISSUE THREAD

**Issue by oke-py** [cloudnativedaysjp/dreamkast#699]
## 概要

dreamkastのローカル開発環境を構築する。

## 参考

https://gist.github.com/jacopen/45d18d2288f992237f0d082ab27e4262

**Comment by oke-py** [comment]
jacopenさんの手順をもとに、nodejsとrubyのインストールにasdfを使うようにした（ただの好み）。
https://gist.github.com/oke-py/4b49c1b519728173e932e09138577067

Cloud9用のSSH公開鍵を用意した。不要になったら削除する。

https://github.com/cloudnativedaysjp/dreamkast#setup-environment
```sh
sudo apt-get install shared-mime-info
cd dreamkast
yarn install --check-files
bundle install
```

`bundle install`で失敗する。
<details>
  <summary>Click to expand!</summary>

```
cat /home/ubuntu/.rvm/gems/ruby-2.6.3/extensions/x86_64-linux/3.0.0/mysql2-0.5.3/gem_make.out
current directory: /home/ubuntu/.rvm/gems/ruby-2.6.3/gems/mysql2-0.5.3/ext/mysql2
/home/ubuntu/.asdf/installs/ruby/3.0.2/bin/ruby -I /home/ubuntu/.asdf/installs/ruby/3.0.2/lib/ruby/3.0.0 -r ./siteconf20211114-23848-xlomnw.rb extconf.rb
checking for rb_absint_size()... yes
checking for rb_absint_singlebit_p()... yes
checking for rb_wait_for_single_fd()... yes
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/home/ubuntu/.asdf/installs/ruby/3.0.2/bin/$(RUBY_BASE_NAME)
        --with-mysql-dir
        --without-mysql-dir
        --with-mysql-include
        --without-mysql-include=${mysql-dir}/include
        --with-mysql-lib
        --without-mysql-lib=${mysql-dir}/lib
        --with-mysql-config
        --without-mysql-config
        --with-mysqlclient-dir
        --without-mysqlclient-dir
        --with-mysqlclient-include
        --without-mysqlclient-include=${mysqlclient-dir}/include
        --with-mysqlclient-lib
        --without-mysqlclient-lib=${mysqlclient-dir}/lib
        --with-mysqlclientlib
        --without-mysqlclientlib
/home/ubuntu/.asdf/installs/ruby/3.0.2/lib/ruby/3.0.0/mkmf.rb:1050:in `block in find_library': undefined method `split' for nil:NilClass (NoMethodError)
        from /home/ubuntu/.asdf/installs/ruby/3.0.2/lib/ruby/3.0.0/mkmf.rb:1050:in `collect'
        from /home/ubuntu/.asdf/installs/ruby/3.0.2/lib/ruby/3.0.0/mkmf.rb:1050:in `find_library'
        from extconf.rb:87:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/ubuntu/.rvm/gems/ruby-2.6.3/extensions/x86_64-linux/3.0.0/mysql2-0.5.3/mkmf.log

extconf failed, exit code 1
```

```
cat /home/ubuntu/.rvm/gems/ruby-2.6.3/extensions/x86_64-linux/3.0.0/mysql2-0.5.3/mkmf.log
have_func: checking for rb_absint_size()... -------------------- yes

"gcc -o conftest -I/home/ubuntu/.asdf/installs/ruby/3.0.2/include/ruby-3.0.0/x86_64-linux -I/home/ubuntu/.asdf/installs/ruby/3.0.2/include/ruby-3.0.0/ruby/backward -I/home/ubuntu/.asdf/installs/ruby/3.0.2/include/ruby-3.0.0 -I. -I/home/ubuntu/.asdf/installs/ruby/3.0.2/include    -O3 -ggdb3 -Wall -Wextra -Wdeprecated-declarations -Wduplicated-cond -Wimplicit-function-declaration -Wimplicit-int -Wmisleading-indentation -Wpointer-arith -Wwrite-strings -Wimplicit-fallthrough=0 -Wmissing-noreturn -Wno-cast-function-type -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-packed-bitfield-compat -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wsuggest-attribute=format -Wsuggest-attribute=noreturn -Wunused-variable  -fPIC conftest.c  -L. -L/home/ubuntu/.asdf/installs/ruby/3.0.2/lib -Wl,-rpath,/home/ubuntu/.asdf/installs/ruby/3.0.2/lib -L. -L/home/ubuntu/.asdf/installs/ruby/3.0.2/lib  -fstack-protector-strong -rdynamic -Wl,-export-dynamic     -Wl,-rpath,/home/ubuntu/.asdf/installs/ruby/3.0.2/lib -L/home/ubuntu/.asdf/installs/ruby/3.0.2/lib -lruby  -lm   -lc"
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return !!argv[argc];
6: }
/* end */

"gcc -o conftest -I/home/ubuntu/.asdf/installs/ruby/3.0.2/include/ruby-3.0.0/x86_64-linux -I/home/ubuntu/.asdf/installs/ruby/3.0.2/include/ruby-3.0.0/ruby/backward -I/home/ubuntu/.asdf/installs/ruby/3.0.2/include/ruby-3.0.0 -I. -I/home/ubuntu/.asdf/installs/ruby/3.0.2/include    -O3 -ggdb3 -Wall -Wextra -Wdeprecated-declarations -Wduplicated-cond -Wimplicit-function-declaration -Wimplicit-int -Wmisleading-indentation -Wpointer-arith -Wwrite-strings -Wimplicit-fallthrough=0 -Wmissing-noreturn -Wno-cast-function-type -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-packed-bitfield-compat -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wsuggest-attribute=format -Wsuggest-attribute=noreturn -Wunused-variable  -fPIC conftest.c  -L. -L/home/ubuntu/.asdf/installs/ruby/3.0.2/lib -Wl,-rpath,/home/ubuntu/.asdf/installs/ruby/3.0.2/lib -L. -L/home/ubuntu/.asdf/installs/ruby/3.0.2/lib  -fstack-protector-strong -rdynamic -Wl,-export-dynamic     -Wl,-rpath,/home/ubuntu/.asdf/installs/ruby/3.0.2/lib -L/home/ubuntu/.asdf/installs/ruby/3.0.2/lib -lruby  -lm   -lc"
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     int (* volatile tp)(void)=(int (*)(void))&t;
 9:     printf("%d", (*tp)());
10:   }
11: 
12:   return !!argv[argc];
13: }
14: int t(void) { void ((*volatile p)()); p = (void ((*)()))rb_absint_size; return !p; }
/* end */

--------------------

have_func: checking for rb_absint_singlebit_p()... -------------------- yes

"gcc -o conftest -I/home/ubuntu/.asdf/installs/ruby/3.0.2/include/ruby-3.0.0/x86_64-linux -I/home/ubuntu/.asdf/installs/ruby/3.0.2/include/ruby-3.0.0/ruby/backward -I/home/ubuntu/.asdf/installs/ruby/3.0.2/include/ruby-3.0.0 -I. -I/home/ubuntu/.asdf/installs/ruby/3.0.2/include    -O3 -ggdb3 -Wall -Wextra -Wdeprecated-declarations -Wduplicated-cond -Wimplicit-function-declaration -Wimplicit-int -Wmisleading-indentation -Wpointer-arith -Wwrite-strings -Wimplicit-fallthrough=0 -Wmissing-noreturn -Wno-cast-function-type -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-packed-bitfield-compat -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wsuggest-attribute=format -Wsuggest-attribute=noreturn -Wunused-variable  -fPIC conftest.c  -L. -L/home/ubuntu/.asdf/installs/ruby/3.0.2/lib -Wl,-rpath,/home/ubuntu/.asdf/installs/ruby/3.0.2/lib -L. -L/home/ubuntu/.asdf/installs/ruby/3.0.2/lib  -fstack-protector-strong -rdynamic -Wl,-export-dynamic     -Wl,-rpath,/home/ubuntu/.asdf/installs/ruby/3.0.2/lib -L/home/ubuntu/.asdf/installs/ruby/3.0.2/lib -lruby  -lm   -lc"
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     int (* volatile tp)(void)=(int (*)(void))&t;
 9:     printf("%d", (*tp)());
10:   }
11: 
12:   return !!argv[argc];
13: }
14: int t(void) { void ((*volatile p)()); p = (void ((*)()))rb_absint_singlebit_p; return !p; }
/* end */

--------------------

have_func: checking for rb_wait_for_single_fd()... -------------------- yes

"gcc -o conftest -I/home/ubuntu/.asdf/installs/ruby/3.0.2/include/ruby-3.0.0/x86_64-linux -I/home/ubuntu/.asdf/installs/ruby/3.0.2/include/ruby-3.0.0/ruby/backward -I/home/ubuntu/.asdf/installs/ruby/3.0.2/include/ruby-3.0.0 -I. -I/home/ubuntu/.asdf/installs/ruby/3.0.2/include    -O3 -ggdb3 -Wall -Wextra -Wdeprecated-declarations -Wduplicated-cond -Wimplicit-function-declaration -Wimplicit-int -Wmisleading-indentation -Wpointer-arith -Wwrite-strings -Wimplicit-fallthrough=0 -Wmissing-noreturn -Wno-cast-function-type -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-packed-bitfield-compat -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wsuggest-attribute=format -Wsuggest-attribute=noreturn -Wunused-variable  -fPIC conftest.c  -L. -L/home/ubuntu/.asdf/installs/ruby/3.0.2/lib -Wl,-rpath,/home/ubuntu/.asdf/installs/ruby/3.0.2/lib -L. -L/home/ubuntu/.asdf/installs/ruby/3.0.2/lib  -fstack-protector-strong -rdynamic -Wl,-export-dynamic     -Wl,-rpath,/home/ubuntu/.asdf/installs/ruby/3.0.2/lib -L/home/ubuntu/.asdf/installs/ruby/3.0.2/lib -lruby  -lm   -lc"
conftest.c: In function ‘t’:
conftest.c:14:57: error: ‘rb_wait_for_single_fd’ undeclared (first use in this function)
 int t(void) { void ((*volatile p)()); p = (void ((*)()))rb_wait_for_single_fd; return !p; }
                                                         ^~~~~~~~~~~~~~~~~~~~~
conftest.c:14:57: note: each undeclared identifier is reported only once for each function it appears in
conftest.c: At top level:
cc1: warning: unrecognized command line option ‘-Wno-self-assign’
cc1: warning: unrecognized command line option ‘-Wno-parentheses-equality’
cc1: warning: unrecognized command line option ‘-Wno-constant-logical-operand’
cc1: warning: unrecognized command line option ‘-Wno-cast-function-type’
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     int (* volatile tp)(void)=(int (*)(void))&t;
 9:     printf("%d", (*tp)());
10:   }
11: 
12:   return !!argv[argc];
13: }
14: int t(void) { void ((*volatile p)()); p = (void ((*)()))rb_wait_for_single_fd; return !p; }
/* end */

"gcc -o conftest -I/home/ubuntu/.asdf/installs/ruby/3.0.2/include/ruby-3.0.0/x86_64-linux -I/home/ubuntu/.asdf/installs/ruby/3.0.2/include/ruby-3.0.0/ruby/backward -I/home/ubuntu/.asdf/installs/ruby/3.0.2/include/ruby-3.0.0 -I. -I/home/ubuntu/.asdf/installs/ruby/3.0.2/include    -O3 -ggdb3 -Wall -Wextra -Wdeprecated-declarations -Wduplicated-cond -Wimplicit-function-declaration -Wimplicit-int -Wmisleading-indentation -Wpointer-arith -Wwrite-strings -Wimplicit-fallthrough=0 -Wmissing-noreturn -Wno-cast-function-type -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-packed-bitfield-compat -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wsuggest-attribute=format -Wsuggest-attribute=noreturn -Wunused-variable  -fPIC conftest.c  -L. -L/home/ubuntu/.asdf/installs/ruby/3.0.2/lib -Wl,-rpath,/home/ubuntu/.asdf/installs/ruby/3.0.2/lib -L. -L/home/ubuntu/.asdf/installs/ruby/3.0.2/lib  -fstack-protector-strong -rdynamic -Wl,-export-dynamic     -Wl,-rpath,/home/ubuntu/.asdf/installs/ruby/3.0.2/lib -L/home/ubuntu/.asdf/installs/ruby/3.0.2/lib -lruby  -lm   -lc"
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: /*top*/
 4: extern int t(void);
 5: int main(int argc, char **argv)
 6: {
 7:   if (argc > 1000000) {
 8:     int (* volatile tp)(void)=(int (*)(void))&t;
 9:     printf("%d", (*tp)());
10:   }
11: 
12:   return !!argv[argc];
13: }
14: extern void rb_wait_for_single_fd();
15: int t(void) { rb_wait_for_single_fd(); return 0; }
/* end */

--------------------
```  
</details>
昨日M1 Macでも遭遇したもの。解決策はごろごろ転がっているが、どれが当たるかやってみないとわからない。

**Comment by oke-py** [comment]
```
sudo apt install libmysqld-dev
bundle install
```
でいけた。
参考 https://qiita.com/GandT/items/bee105afe228a564a4da

**Comment by oke-py** [comment]
Cloud9環境をt2.microで作成してしばらくしたら反応がなくなった。CPU使いすぎ。
c5.largeで作成したら改善したものの、EBS 10GBでは`docker-compose pull`する頃にはno space on left
停止してサイズ拡張しようとしたら間違えてインスタンスを終了してしまった模様。

**Comment by oke-py** [comment]
```
$ aws ecr get-login-password | docker login --username AWS --password-stdin http://607167088920.dkr.ecr.ap-northeast-1.amazonaws.com/
Error saving credentials: error storing credentials - err: exit status 1, out: `Cannot autolaunch D-Bus without X11 $DISPLAY`
```
となった。昨日はならなかった。昨日の手順との差異は先に`sudo apt install docker-compose`したこと。

https://stackoverflow.com/questions/51222996/docker-login-fails-on-a-server-with-no-x11-installed を参考に
```
sudo apt install gnupg2 pass
```
したら解決した。

**Comment by oke-py** [comment]
```
$ docker-compose up -d db redis nginx ui
ERROR: for dreamkast_db_1  Cannot start service db: driver failed programming external connectivity on endpoint dreamkast_db_1 (5b672a09723889b446968Creating dreamkast_redis_1 ... done

ERROR: for db  Cannot start service db: driver failed programming external connectivity on endpoint dreamkast_db_1 (5b672a09723889b4469686cbf3ad46b02b71220a948cf8c73e3d76874406d013): Error starting userland proxy: listen tcp4 0.0.0.0:3306: bind: address already in use
ERROR: Encountered errors while bringing up the project.
```
Cloud9ではmysqldが起動しているらしい。
```
sudo service mysql stop
```

**Comment by oke-py** [comment]
むむ
```
$ bundle exec rails db:create RAILS_ENV=test
["/home/ubuntu/environment/workspace/dreamkast/db/fixtures", "/home/ubuntu/environment/workspace/dreamkast/db/fixtures/test"]
DEPRECATION WARNING: Initialization autoloaded the constant RescueFromInvalidAuthenticityToken.

Being able to do this is deprecated. Autoloading during initialization is going
to be an error condition in future versions of Rails.

Reloading does not reboot the application, and therefore code executed during
initialization does not run again. So, if you reload RescueFromInvalidAuthenticityToken, for example,
the expected changes won't be reflected in that stale Class object.

This autoloaded constant has been unloaded.

Please, check the "Autoloading and Reloading Constants" guide for solutions.
 (called from <main> at /home/ubuntu/environment/workspace/dreamkast/config/environment.rb:5)
Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
Couldn't create 'dreamkast_test' database. Please check your configuration.
rails aborted!
Mysql2::Error::ConnectionError: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
/home/ubuntu/environment/workspace/dreamkast/bin/rails:9:in `<top (required)>'
/home/ubuntu/environment/workspace/dreamkast/bin/spring:15:in `require'
/home/ubuntu/environment/workspace/dreamkast/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:create
(See full trace by running task with --trace)
```

**Comment by oke-py** [comment]
https://qiita.com/KOBA-RYOTA/items/3cf5070b54845e151034 を参考にMYSQL_HOSTにIPを指定するとOK
DEPRECATION WARNINGが出るが、exit codeは0だった。
```
$ bundle exec rails db:create RAILS_ENV=test
["/home/ubuntu/environment/workspace/dreamkast/db/fixtures", "/home/ubuntu/environment/workspace/dreamkast/db/fixtures/test"]
DEPRECATION WARNING: Initialization autoloaded the constant RescueFromInvalidAuthenticityToken.

Being able to do this is deprecated. Autoloading during initialization is going
to be an error condition in future versions of Rails.

Reloading does not reboot the application, and therefore code executed during
initialization does not run again. So, if you reload RescueFromInvalidAuthenticityToken, for example,
the expected changes won't be reflected in that stale Class object.

This autoloaded constant has been unloaded.

Please, check the "Autoloading and Reloading Constants" guide for solutions.
 (called from <main> at /home/ubuntu/environment/workspace/dreamkast/config/environment.rb:5)
Created database 'dreamkast_test'

$ bundle exec rails db:environment:set RAILS_ENV=test
["/home/ubuntu/environment/workspace/dreamkast/db/fixtures", "/home/ubuntu/environment/workspace/dreamkast/db/fixtures/test"]
DEPRECATION WARNING: Initialization autoloaded the constant RescueFromInvalidAuthenticityToken.

Being able to do this is deprecated. Autoloading during initialization is going
to be an error condition in future versions of Rails.

Reloading does not reboot the application, and therefore code executed during
initialization does not run again. So, if you reload RescueFromInvalidAuthenticityToken, for example,
the expected changes won't be reflected in that stale Class object.

This autoloaded constant has been unloaded.

Please, check the "Autoloading and Reloading Constants" guide for solutions.
 (called from <main> at /home/ubuntu/environment/workspace/dreamkast/config/environment.rb:5)
```

**Comment by oke-py** [comment]
config/environments/development.rbに追加した。
```
config.hosts << "cloud9 previewのFQDN"
```

jacopenさんに教えてもらったやつ
```
bundle exec rails db:create RAILS_ENV=test
bundle exec rails db:environment:set RAILS_ENV=test
./entrypoint.sh
```
`rails db:migrate RAILS_ENV=development`せよとエラーが出た。
```
bundle exec rails db:migrate RAILS_ENV=development
bundle exec rails db:seed RAILS_ENV=development
./entrypoint.sh 
```
いけた！
